databases:
  - name: amc-db
    plan: free

services:
  - type: web
    name: amc-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amc-db
          property: connectionString
      - key: ADMIN_KEY
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: META_APP_ID
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: META_CONFIG_ID
        value: "1696605061677781"
      - key: META_GRAPH_API_VERSION
        value: v21.0
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CONTACT_NUMBER
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: amc-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
